blank_issues_enabled: true
contact_links:
  - name: 🌊 WaveOps Documentation
    url: https://github.com/flyingrobots/waveops/blob/main/docs/README.md
    about: Read the complete WaveOps documentation and guides
  - name: 💬 GitHub Discussions
    url: https://github.com/flyingrobots/waveops/discussions
    about: Ask questions and discuss WaveOps with the community
  - name: 🚨 Report Security Issue
    url: https://github.com/flyingrobots/waveops/security/advisories/new
    about: Report security vulnerabilities privately