apiVersion: v1
kind: Namespace
metadata:
  name: waveops
  labels:
    name: waveops
    app.kubernetes.io/name: waveops
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: coordination
    app.kubernetes.io/part-of: waveops
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    kubernetes.io/managed-by: "waveops-operator"
    description: "WaveOps Enterprise Scaling Namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: waveops-resource-quota
  namespace: waveops
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: waveops-limit-range
  namespace: waveops
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim